// DECLARING AN ENUM FOR THE APPSTATEREDUCERFUNCTION ACTION
export enum APP_STATE_REDUCER_ACTION_TYPE{
    INCREASE_COUNT = "INCREASE_COUNT",
    DECREASE_COUNT = "DECREASE_COUNT",
    UPDATE_NAME = "UPDATE_NAME",
}