// AN ENUM FOR THE PRODUCTSCONTEXTREDUCERACTION TYPE
export enum PRODUCTS_CONTEXT_REDUCER_ACTION_TYPE{
    CREATE_PRODUCTS = "CREATE_PRODUCTS",
    ADD_PRODUCT = "ADD_PRODUCT",
    UPDATE_PRODUCT = "UPDATE_PRODUCT",
    UPDATE_ALL_PRODUCTS = "UPDATE_ALL_PRODUCTS",
    DELETE_PRODUCT = "DELETE_PRODUCT",
    DELETE_ALL_PRODUCTS = "DELETE_ALL_PRODUCTS"
}

// AN ENUM FOR THE CARTCONTEXTREDUCERACTION TYPE
export enum CART_CONTEXT_REDUCER_ACTION_TYPE{
    ADD_TO_CART = "ADD_TO_CART",
    EMPTY_CART = "EMPTY_CART",
    ADD_QUANTITY_TO_CART = "ADD_QUANTITY_TO_CART",
    REMOVE_FROM_CART = "REMOVE_FROM_CART",
    ADD_EVERY_QUANTITY_TO_CART = "ADD_EVERY_QUANTITY_TO_CART",
}